Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "devbus"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "devbus"
    vb.memory = "4096"
  end

  config.vm.network "private_network", ip: "192.168.33.211"

  config.vm.provision "shell", path: "devbus.sh"
end
