
variable "esclavo_memory" {
  type    = string
  default = "2048"
}

variable "jenkins_ip" {
  type    = string
  default = "192.168.33.60"
}

variable "jenkins_memory" {
  type    = string
  default = "4096"
}

variable "jenkins_public_ip" {
  type    = string
  default = "172.16.1.60"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command     = ["<wait>c<wait>set gfxpayload=keep<enter><wait>linux /casper/vmlinuz quiet autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ubuntu/ ---<enter><wait>initrd /casper/initrd<wait><enter><wait>boot<enter><wait> umount /dev/sr0<enter><wait>reboot<wait>"]
  boot_wait        = "5s"
  disk_size        = "100000"
  guest_os_type    = "Ubuntu_64"
  headless         = false
  http_directory   = "http"
  iso_checksum     = "file:https://releases.ubuntu.com/jammy/SHA256SUMS"
  iso_url          = "https://releases.ubuntu.com/jammy/ubuntu-22.04.2-live-server-amd64.iso"
  memory           = 4096
  output_directory = "output-${var.jenkins_ip}"
  shutdown_command = "echo 'packer' | sudo -S shutdown -P now"
  ssh_password     = "packer"
  ssh_port         = 22
  ssh_username     = "packer"
  vm_name          = "jenkins"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'packer' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script          = "scripts/jenkins.sh"
  }

}
