Vagrant.configure("2") do |config|
  config.vm.define "puppetserver" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "puppetserver"
    server.vm.network "private_network", ip: "192.168.33.10"
    server.vm.provision "shell", path: "server.sh"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "puppetserver"
      vb.memory = 4096  # Asigna 4 GB de memoria RAM
      vb.cpus = 2
    end   
  end


    config.vm.define "node1" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "puppetnode1"
      node.vm.network "private_network", ip: "192.168.33.11"
      node.vm.provision "shell", path: "cliente.sh"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node1"
        vb.memory = 2048
      end   
    end


end
