version: '3.7'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: bd_wp
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: CaM1n0K0yoT3
      MYSQL_ROOT_PASSWORD: CaM1n0K0yoT3
    volumes:
      - /opt/mysql_wp:/var/lib/mysql
 
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: CaM1n0K0yoT3
      WORDPRESS_DB_NAME: bd_wp
    ports:
      - "80:80"
    volumes:
      - /opt/wordpress:/var/www/html/wp-content
