- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: clave-paris1265
        instance_type: t3.micro
        image: ami-05b5a865c3579bbc4
        wait: True
        region: eu-west-3
        count: 1
      register: ec2_instance

    - name: Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ec2_instances
      with_items: "{{ ec2_instance.instances }}"

    - name: Add tags to EC2 instance
      ec2_tag:
        resource: "{{ item.id }}"
        region: eu-west-3
        state: present
        tags:
          Name: MyEC2Instance
          Environment: Production
      with_items: "{{ ec2_instance.instances }}"

- name: Configure EC2 instance
  hosts: ec2_instances
  remote_user: ubuntu
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
