- name: Instalar Apache
  hosts: "{{ host }}"
  gather_facts: yes
  tasks:
    - name: Instalar Apache en sistemas CentOS/Red Hat
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Instalar Apache en sistemas Debian/Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
