# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Configuración de la máquina virtual master con Ansible instalado
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = 2048  # Asigna 2 GB de memoria RAM

    end
    master.vm.provision "shell", path: "master.sh"

  end

  # Configuración de la máquina virtual docker con Docker instalado
  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/jammy64"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.33.20"
    docker.vm.provider "virtualbox" do |vb|
      vb.name = "docker"
      vb.memory = 2048  # Asigna 2 GB de memoria RAM

    end
    docker.vm.provision "shell", path: "docker.sh"

  end

  # Configuración de dos máquinas virtuales objetivo
  (1..3).each do |i|
    config.vm.define "objetivo#{i}" do |objetivo|
      objetivo.vm.box = "ubuntu/jammy64"
      objetivo.vm.hostname = "objetivo#{i}"
      objetivo.vm.network "private_network", ip: "192.168.33.#{i+20}"
      objetivo.vm.provider "virtualbox" do |vb|
        vb.name = "objetivo#{i}"
        vb.memory = 1024  # Asigna 1 GB de memoria RAM

      end
      objetivo.vm.provision "shell", path: "objetivo.sh"
    end
  end

end
