apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      image: tutum/hello-world
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      stdin: true
      tty: true
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
